subjects = ['c', 'c++', 'java', 'python', 'html', 'css', 'js']
# subjects.append("jquery")
# subjects.insert(2, 'mysql')
# subjects.remove('js')
# subjects.sort()
# subjects.reverse()
# subjects.pop()
# subjects.pop()
# subjects.clear()
# subjects2=subjects.copy()
# print(subjects2)
# pos=subjects.index('js')
# print(pos)
count=subjects.count('js')
print(count)